name: Contribution Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest
    name: Generate Contribution Stats
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: esadkrs
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          
      - name: Generate Contribution Graph
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: esadkrs

      - name: Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update contribution stats" || echo "No changes to commit"
          git push