name: GitHub Stats Update

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate GitHub Stats Images
        uses: anuraghazra/github-readme-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          USERNAME: esadkrs
          INCLUDE_ALL_COMMITS: true
          COUNT_PRIVATE: true
          SHOW_ICONS: true
          THEME: dark
          CACHE_SECONDS: 1800
          
      - name: Generate Additional Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: esadkrs
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Istanbul
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_threshold: B
          plugin_notable: yes
          commits_authoring: esadkiris@gmail.com